	{if rand 0.017 {delay 0.1 {tex_mod "face1"}}	;face; 59 faces, 
	else rand 0.017 {delay 0.1 {tex_mod "face2"}}
	else rand 0.017 {delay 0.1 {tex_mod "face3"}}
	else rand 0.017 {delay 0.1 {tex_mod "face4"}}
	else rand 0.017 {delay 0.1 {tex_mod "face5"}}
	else rand 0.017 {delay 0.1 {tex_mod "face6"}}
	else rand 0.017 {delay 0.1 {tex_mod "face7"}}
	else rand 0.017 {delay 0.1 {tex_mod "face8"}}
	else rand 0.017 {delay 0.1 {tex_mod "face9"}}
	else rand 0.017 {delay 0.1 {tex_mod "face10"}}
	else rand 0.017 {delay 0.1 {tex_mod "face11"}}
	else rand 0.017 {delay 0.1 {tex_mod "face12"}}
	else rand 0.017 {delay 0.1 {tex_mod "face13"}}
	else rand 0.017 {delay 0.1 {tex_mod "face14"}}
	else rand 0.017 {delay 0.1 {tex_mod "face15"}}
	else rand 0.017 {delay 0.1 {tex_mod "face16"}}
	else rand 0.017 {delay 0.1 {tex_mod "face17"}}
	else rand 0.017 {delay 0.1 {tex_mod "face18"}}
	else rand 0.017 {delay 0.1 {tex_mod "face19"}}
	else rand 0.017 {delay 0.1 {tex_mod "face20"}}
	else rand 0.017 {delay 0.1 {tex_mod "face21"}}
	else rand 0.017 {delay 0.1 {tex_mod "face22"}}
	else rand 0.017 {delay 0.1 {tex_mod "face23"}}
	else rand 0.017 {delay 0.1 {tex_mod "face24"}}
	else rand 0.017 {delay 0.1 {tex_mod "face25"}}
	else rand 0.017 {delay 0.1 {tex_mod "face26"}}
	else rand 0.017 {delay 0.1 {tex_mod "face27"}}
	else rand 0.017 {delay 0.1 {tex_mod "face28"}}
	else rand 0.017 {delay 0.1 {tex_mod "face29"}}
	else rand 0.017 {delay 0.1 {tex_mod "face30"}}
	else rand 0.017 {delay 0.1 {tex_mod "face31"}}
	else rand 0.017 {delay 0.1 {tex_mod "face32"}}
	else rand 0.017 {delay 0.1 {tex_mod "face33"}}
	else rand 0.017 {delay 0.1 {tex_mod "face34"}}
	else rand 0.017 {delay 0.1 {tex_mod "face35"}}
	else rand 0.017 {delay 0.1 {tex_mod "face36"}}
	else rand 0.017 {delay 0.1 {tex_mod "face37"}}
	else rand 0.017 {delay 0.1 {tex_mod "face38"}}
	else rand 0.017 {delay 0.1 {tex_mod "face39"}}
	else rand 0.017 {delay 0.1 {tex_mod "face40"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest2"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest3"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest4"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest5"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest6"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest7"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest8"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest9"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest10"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest11"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest12"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest13"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest14"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest15"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest16"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest17"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest18"}}
	else rand 0.017 {delay 0.1 {tex_mod "gertest19"}}
	}
{if not tagged "texmod_set"
	{if rand 0.5 {delay 0.1 {tex_mod "eng-var1"}}
	}
	{if rand 0.3 {delay 0.1 {tex_mod "heer_splitter"}}}

	{if rand 0.3 {delay 0.1 {tex_mod "heer_sump1"}}
	else rand 0.2 {delay 0.1 {tex_mod "heer_sump2"}}
	}

	{if rand 0.16 {delay 0.1 {tex_mod "volks1"}}	;volks
	else rand 0.16 {delay 0.1 {tex_mod "volks2"}}
	else rand 0.16 {delay 0.1 {tex_mod "volks3"}}
	else rand 0.16 {delay 0.1 {tex_mod "volks4"}}
	else rand 0.16 {delay 0.1 {tex_mod "volks5"}}
	}
	{if rand 0.25 {delay 0.1 {tex_mod "volks_ober1"}} ;volks oberschutze
	else rand 0.25 {delay 0.1 {tex_mod "volks_ober2"}}
	else rand 0.25 {delay 0.1 {tex_mod "volks_ober3"}}
	}

	{if rand 0.125 {delay 0.1 {tex_mod "volksnco1"}} ;volks nco
	else rand 0.125 {delay 0.1 {tex_mod "volksnco2"}}
	else rand 0.125 {delay 0.1 {tex_mod "volksnco3"}}
	else rand 0.125 {delay 0.1 {tex_mod "volksnco4"}}
	else rand 0.125 {delay 0.1 {tex_mod "volksnco5"}}
	else rand 0.125 {delay 0.1 {tex_mod "volksnco6"}}
	else rand 0.125 {delay 0.1 {tex_mod "volksnco7"}}
	}

	{if rand 0.2 {delay 0.1 {tex_mod "volk_smock1"}} ;volks smock
	else rand 0.2 {delay 0.1 {tex_mod "volk_smock2"}}
	else rand 0.1 {delay 0.1 {tex_mod "volk_smock3"}}
	else rand 0.1 {delay 0.1 {tex_mod "volk_smock4"}}
	else rand 0.1 {delay 0.1 {tex_mod "volk_smock5"}}
	}
	
	{if rand 0.333 {delay 0.1 {tex_mod "pio1"}}	;3 skins
	else rand 0.333 {delay 0.1 {tex_mod "pio2"}}
	}
	
	{if rand 0.5 {delay 0.1 {tex_mod "zelt1"}}	;2 skins
	}
	{if rand 0.333 {delay 0.1 {tex_mod "tk1"}}	;3 skins
	else rand 0.333 {delay 0.1 {tex_mod "tk2"}}
	}
	{if rand 0.25 {delay 0.1 {tex_mod "lssah1"}}	;4 skins
	else rand 0.25 {delay 0.1 {tex_mod "lssah2"}}
	else rand 0.25 {delay 0.1 {tex_mod "lssah3"}}
	}
	{if rand 0.25 {delay 0.1 {tex_mod "ssvt1"}}	;4 skins
	else rand 0.25 {delay 0.1 {tex_mod "ssvt2"}}
	else rand 0.25 {delay 0.1 {tex_mod "ssvt3"}}
	}
	;{if rand 0.2 {delay 0.1 {tex_mod "pe1"}}	;5 skins
	;else rand 0.2 {delay 0.1 {tex_mod "pe2"}}
	;else rand 0.2 {delay 0.1 {tex_mod "pe3"}}
	;else rand 0.2 {delay 0.1 {tex_mod "pe4"}}
	;}
	
	{if rand 0.333 {delay 0.1 {tex_mod "ss1"}}	;3 skins
	else rand 0.333 {delay 0.1 {tex_mod "ss2"}}
	}

	
	
	
	{if rand 0.2 {delay 0.1 {tex_mod "shock1"}}	;5 skins
	else rand 0.2 {delay 0.1 {tex_mod "shock2"}}
	else rand 0.2 {delay 0.1 {tex_mod "shock3"}}
	else rand 0.2 {delay 0.1 {tex_mod "shock4"}}
	}
	{if rand 0.2 {delay 0.1 {tex_mod "par1"}}	;5 skins
	else rand 0.2 {delay 0.1 {tex_mod "par2"}}
	else rand 0.2 {delay 0.1 {tex_mod "par3"}}
	else rand 0.2 {delay 0.1 {tex_mod "par4"}}
	}
}