
			{"allies_usa"
				{title "mp/alliance/allies_usa"}
				{armies "usa"}
				{icon "/interface/pages/multi/flag_usa"}
			}
			{"allies_eng"
				{title "mp/alliance/allies_eng"}
				{armies "eng"}
				{icon "/interface/pages/multi/flag_eng"}
			}
			{"allies_soviet"
				{title "mp/alliance/allies_soviet"}
				{armies "rus"}
				{icon "/interface/pages/multi/flag_rus"}
			}
			{"allies_guards"
				{title "mp/alliance/allies_guards"}
				{armies "rus_guard"}
				{icon "/interface/pages/multi/flag_rus_guard"}
			}
			{"axis_ger" 
				{title "mp/alliance/axis_ger"}
				{armies "ger"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"axis_ss" 
				{title "mp/alliance/axis_ss"}
				{armies "ger_ss"}
				{icon "/interface/pages/multi/flag_ger_ss"}
			}
			{"axis_ger2" 
				{title "mp/alliance/axis_ger2"}
				{armies "ger2"}
				{icon "/interface/pages/multi/flag_ger2"}
			}
			{"axis_jap" 
				{title "mp/alliance/axis_jap"}
				{armies "jap"}
				{icon "/interface/pages/multi/flag_jap"}
			}
			{"axis_ger-ss" 
				{title "mp/alliance/axis_ger-ss"}
				{armies "ger"}
				{armies "ger_ss"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"axis_realistic" 
				{title "mp/alliance/axis_realistic"}
				{armies "ger"}
				{armies "ger2"}
				{armies "ger_ss"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"allies_realistic"
				{title "mp/alliance/allies_realistic"}
				{armies "usa"}
				{armies "eng"}
				{icon "/interface/pages/multi/flag_allies_realistic"}
			}
			{"allies_rus"
				{title "mp/alliance/allies_rus"}
				{armies "rus"}
				{armies "rus_guard"}
				{icon "/interface/pages/multi/flag_rus"}
			}
			{"axis" 
				{title "mp/alliance/axis"}
				{armies "ger"}
				{armies "ger2"}
				{armies "jap"}
				{armies "ger_ss"}
				{icon "/interface/pages/multi/flag_axis"}
			}
			{"allies"
				{title "mp/alliance/allies"}
				{armies "usa"}
				{armies "eng"}
				{armies "rus"}
				{armies "rus_guard"}
				{icon "/interface/pages/multi/flag_allies"}
			}