			{"axis_ger" 
				{title "mp/alliance/axis_ger"}
				{armies "ger"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"allies_usa"
				{title "mp/alliance/allies_usa"}
				{armies "usa"}
				{icon "/interface/pages/multi/flag_usa"}
			}
			{"allies_eng"
				{title "mp/alliance/allies_eng"}
				{armies "eng"}
				{icon "/interface/pages/multi/flag_eng"}
			}
			{"allies_soviet"
				{title "mp/alliance/allies_soviet"}
				{armies "rus"}
				{icon "/interface/pages/multi/flag_rus"}
			}
			{"allies_guards"
				{title "mp/alliance/allies_guards"}
				{armies "rus_guard"}
				{icon "/interface/pages/multi/flag_rus_guard"}
			}
			{"axis_ss" 
				{title "mp/alliance/axis_ss"}
				{armies "ger_ss"}
				{icon "/interface/pages/multi/flag_ger_ss"}
			}
			{"axis_ger2" 
				{title "mp/alliance/axis_ger2"}
				{armies "ger2"}
				{icon "/interface/pages/multi/flag_ger2"}
			}
			{"axis_jap" 
				{title "mp/alliance/axis_jap"}
				{armies "jap"}
				{icon "/interface/pages/multi/flag_jap"}
			}
			
			
			{"axis_realistic" 
				{title "mp/alliance/axis_realistic"}
				{armies "ger"}
				{armies "ger2"}
				{armies "ger_ss"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"axis_ger-ger2" 
				{title "mp/alliance/axis_ger-ger2"}
				{armies "ger"}
				{armies "ger2"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"axis_ger-ss" 
				{title "mp/alliance/axis_ger-ss"}
				{armies "ger"}
				{armies "ger_ss"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"axis_ss-ger2" 
				{title "mp/alliance/axis_ss-ger2"}
				{armies "ger_ss"}
				{armies "ger2"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"allies_realistic"
				{title "mp/alliance/allies_realistic"}
				{armies "usa"}
				{armies "eng"}
				{icon "/interface/pages/multi/flag_allies_realistic"}
			}
			{"allies_rus"
				{title "mp/alliance/allies_rus"}
				{armies "rus"}
				{armies "rus_guard"}
				{icon "/interface/pages/multi/flag_rus"}
			}
			{"axis" 
				{title "mp/alliance/axis"}
				{armies "ger"}
				{armies "ger2"}
				{armies "jap"}
				{armies "ger_ss"}
				{icon "/interface/pages/multi/flag_axis"}
			}
			{"allies"
				{title "mp/alliance/allies"}
				{armies "usa"}
				{armies "eng"}
				{armies "rus"}
				{armies "rus_guard"}
				{icon "/interface/pages/multi/flag_allies"}
			}
			{"axis_doctrines" 
				{title "mp/alliance/axis_doctrines"}
				{armies "ger_doc_a"}
				{armies "ger_doc_ad"}
				{armies "ger_doc_am"}
				{armies "ger_doc_bt"}
				{armies "ger_doc_f"}
				{armies "ger_doc_hp"}
				{armies "ger_doc_i"}
				{armies "ger_doc_luft"}
				{armies "ger_doc_p"}
				{armies "ger_doc_pj"}
				{armies "ger_doc_ps"}
				{armies "ger_doc_r"}
				{armies "ger_doc_rt"}
				{armies "ger_doc_sh"}
				;{armies "ger_ss"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"allies_doctrines" 
				{title "mp/alliance/allies_doctrines"}
				;{armies "rus_doc_a"}
				;{armies "rus_doc_art"}
				;{armies "rus_doc_as"}
				;{armies "rus_doc_d"}
				;{armies "rus_doc_db"}
				;{armies "rus_doc_g"}
				;{armies "rus_doc_ha"}
				;{armies "rus_doc_i"}
				;{armies "rus_doc_lis"}
				;{armies "rus_doc_s"}
				;{armies "rus_doc_td"}
				;{armies "rus_doc_uc"}
				
				{armies "usa_doc_a"}
				{armies "usa_doc_art"}
				{armies "usa_doc_ca"}
				{armies "usa_doc_d"}
				{armies "usa_doc_et"}
				{armies "usa_doc_hs"}
				{armies "usa_doc_i"}
				{armies "usa_doc_mc"}
				{armies "usa_doc_para"}
				{armies "usa_doc_ta"}
				{armies "usa_doc_td"}
				{icon "/interface/pages/multi/flag_allies"}
			}