	{level "lvl_1"		;Soviet conscripts and German volkssturm
		{stand
			{accuracy 0.30}
		}
		{squat
			{accuracy 0.45}
		}
		{crawl
			{accuracy 0.55}
		}
		{cover
			{accuracy 0.60}
		}
	}
	{level "lvl_2"		;Jap basic infantry, soviet basic infantry pre 43
		{stand
			{accuracy 0.40}
		}
		{squat
			{accuracy 0.60}
		}
		{crawl
			{accuracy 0.70}
		}
		{cover
			{accuracy 0.75}
		}
	}
	{level "lvl_3"		;US/brit basic infantry, late soviet inf post 42
		{stand
			{accuracy 0.50}
		}
		{squat
			{accuracy 0.70}
		}
		{crawl
			{accuracy 0.80}
		}
		{cover
			{accuracy 0.85}
		}
	}
	{level "lvl_4"		;German basic infantry, post42 brit inf
		{stand
			{accuracy 0.60}
		}
		{squat
			{accuracy 0.80}
		}
		{crawl
			{accuracy 0.90}
		}
		{cover
			{accuracy 0.95}
		}
	}
	{level "lvl_5"
		{stand
			{accuracy 0.70}
		}
		{squat
			{accuracy 0.95}
		}
		{crawl
			{accuracy 1.05}
		}
		{cover
			{accuracy 1.10}
		}
	}
	{level "lvl_6"
		{stand
			{accuracy 0.80}
		}
		{squat
			{accuracy 1.08}
		}
		{crawl
			{accuracy 1.18}
		}
		{cover
			{accuracy 1.23}
		}
	}
	{level "lvl_7"
		{stand
			{accuracy 0.90}
		}
		{squat
			{accuracy 1.21}
		}
		{crawl
			{accuracy 1.31}
		}
		{cover
			{accuracy 1.36}
		}
	}
	{level "lvl_8"
		{stand
			{accuracy 1.00}
		}
		{squat
			{accuracy 1.34}
		}
		{crawl
			{accuracy 1.44}
		}
		{cover
			{accuracy 1.49}
		}
	}
	{level "lvl_9"
		{stand
			{accuracy 1.10}
		}
		{squat
			{accuracy 1.47}
		}
		{crawl
			{accuracy 1.57}
		}
		{cover
			{accuracy 1.62}
		}
	}
	{level "lvl_10"
		{stand
			{accuracy 1.20}
		}
		{squat
			{accuracy 1.60}
		}
		{crawl
			{accuracy 1.70}
		}
		{cover
			{accuracy 1.75}
		}
	}