(define "veterancy_1"
		{"lvl_1" 2
		}
		{"lvl_2" 5
		}
		{"lvl_3" 9
		}
		{"lvl_4" 14
		}
		{"lvl_5" 20
		}
		(mod "mp"
			{"lvl_1" 2
			}
			{"lvl_2" 5
			}
			{"lvl_3" 9
			}
			{"lvl_4" 14
			}
			{"lvl_5" 20
			}
		)
)
(define "veterancy_tankcrew"
		{"lvl_1" 5
		}
		{"lvl_2" 11
		}
		{"lvl_3" 18
		}
		{"lvl_4" 26
		}
		{"lvl_5" 35
		}
		(mod "mp"
			{"lvl_1" 7
			}
			{"lvl_2" 15
			}
			{"lvl_3" 30
			}
			{"lvl_4" 45
			}
			{"lvl_5" 60
			}
		)
)
(define "veterancy_elite"
		{"lvl_1" 5
		}
		{"lvl_2" 11
		}
		{"lvl_3" 18
		}
		{"lvl_4" 26
		}
		{"lvl_5" 35
		}
		(mod "mp"
			{"lvl_1" 5
			}
			{"lvl_2" 11
			}
			{"lvl_3" 18
			}
			{"lvl_4" 26
			}
			{"lvl_5" 35
			}
		)
)
(define "veterancy_lvl5"
		{"lvl_1" -1
		}
		{"lvl_2" -1
		}
		{"lvl_3" -1
		}
		{"lvl_4" -1
		}
		{"lvl_5" 0
		}
)

(define "veterancy_1_old"
		{"lvl_1" 4
		}
		{"lvl_2" 8
		}
		{"lvl_3" 24
		}
		{"lvl_4" 48
		}
		{"lvl_5" 80
		}
		(mod "mp"
			{"lvl_1" 2
			}
			{"lvl_2" 5
			}
			{"lvl_3" 9
			}
			{"lvl_4" 14
			}
			{"lvl_5" 20
			}
		)
)