(define "veterancy_1"
		{"lvl_1" 2
		}
		{"lvl_2" 5
		}
		{"lvl_3" 9
		}
		{"lvl_4" 14
		}
		{"lvl_5" 20
		}
		(mod "mp"
			{"lvl_1" 2
			}
			{"lvl_2" 5
			}
			{"lvl_3" 9
			}
			{"lvl_4" 14
			}
			{"lvl_5" 20
			}
		)
)
(define "veterancy_1_lvl1"
		{"lvl_1" 0
		}
		{"lvl_2" 4
		}
		{"lvl_3" 9
		}
		{"lvl_4" 12
		}
		{"lvl_5" 17
		}
)
(define "veterancy_1_lvl2"
		{"lvl_1" -1
		}
		{"lvl_2" 0
		}
		{"lvl_3" 4
		}
		{"lvl_4" 10
		}
		{"lvl_5" 16
		}
)
(define "veterancy_1_lvl3"
		{"lvl_1" -1
		}
		{"lvl_2" -1
		}
		{"lvl_3" 0
		}
		{"lvl_4" 6
		}
		{"lvl_5" 12
		}
)
(define "veterancy_lvl5"
		{"lvl_1" -1
		}
		{"lvl_2" -1
		}
		{"lvl_3" -1
		}
		{"lvl_4" -1
		}
		{"lvl_5" 0
		}
)
(define "veterancy_tankcrew"
		{"lvl_1" 5
		}
		{"lvl_2" 11
		}
		{"lvl_3" 18
		}
		{"lvl_4" 26
		}
		{"lvl_5" 35
		}
		(mod "mp"
			{"lvl_1" 7
			}
			{"lvl_2" 15
			}
			{"lvl_3" 30
			}
			{"lvl_4" 45
			}
			{"lvl_5" 60
			}
		)
)
(define "veterancy_tankcrew_lvl3"
		{"lvl_1" -1
		}
		{"lvl_2" -1
		}
		{"lvl_3" 0
		}
		{"lvl_4" 8
		}
		{"lvl_5" 17
		}
		(mod "mp"
			{"lvl_1" -1
			}
			{"lvl_2" -1
			}
			{"lvl_3" 0
			}
			{"lvl_4" 15
			}
			{"lvl_5" 30
			}
		)
)
(define "veterancy_elite"
		{"lvl_1" 5
		}
		{"lvl_2" 11
		}
		{"lvl_3" 18
		}
		{"lvl_4" 26
		}
		{"lvl_5" 35
		}
		(mod "mp"
			{"lvl_1" 5
			}
			{"lvl_2" 11
			}
			{"lvl_3" 18
			}
			{"lvl_4" 26
			}
			{"lvl_5" 35
			}
		)
)