(define "veterancy_1"
		{"lvl_1" 2
		}
		{"lvl_2" 5
		}
		{"lvl_3" 9
		}
		{"lvl_4" 14
		}
		{"lvl_5" 20
		}
		{"lvl_6" 28
		}
		{"lvl_7" 38
		}
		{"lvl_8" 50
		}
		{"lvl_9" 64
		}
		{"lvl_10" 80
		}
)
(define "veterancy_1_lvl1"
		{"lvl_1" 0
		}
		{"lvl_2" 4
		}
		{"lvl_3" 9
		}
		{"lvl_4" 12
		}
		{"lvl_5" 17
		}
		{"lvl_6" 24
		}
		{"lvl_7" 33
		}
		{"lvl_8" 44
		}
		{"lvl_9" 57
		}
		{"lvl_10" 72
		}
)
(define "veterancy_1_lvl2"
		{"lvl_1" -1
		}
		{"lvl_2" 0
		}
		{"lvl_3" 4
		}
		{"lvl_4" 10
		}
		{"lvl_5" 16
		}
		{"lvl_6" 24
		}
		{"lvl_7" 34
		}
		{"lvl_8" 46
		}
		{"lvl_9" 60
		}
		{"lvl_10" 78
		}
)
(define "veterancy_1_lvl3"
		{"lvl_1" -1
		}
		{"lvl_2" -1
		}
		{"lvl_3" 0
		}
		{"lvl_4" 6
		}
		{"lvl_5" 12
		}
		{"lvl_6" 20
		}
		{"lvl_7" 30
		}
		{"lvl_8" 42
		}
		{"lvl_9" 56
		}
		{"lvl_10" 72
		}
)
(define "veterancy_tankcrew"
		{"lvl_1" 2
		}
		{"lvl_2" 5
		}
		{"lvl_3" 9
		}
		{"lvl_4" 14
		}
		{"lvl_5" 20
		}
		{"lvl_6" 28
		}
		{"lvl_7" 38
		}
		{"lvl_8" 50
		}
		{"lvl_9" 64
		}
		{"lvl_10" 80
		}
		(mod "mp"
			{"lvl_1" 5
			}
			{"lvl_2" 11
			}
			{"lvl_3" 18
			}
			{"lvl_4" 26
			}
			{"lvl_5" 35
			}
			{"lvl_6" 45
			}
			{"lvl_7" 56
			}
			{"lvl_8" 68
			}
			{"lvl_9" 80
			}
			{"lvl_10" 93
			}
		)
)
(define "veterancy_tankcrew_lvl3"
		{"lvl_1" -1
		}
		{"lvl_2" -1
		}
		{"lvl_3" 0
		}
		{"lvl_4" 6
		}
		{"lvl_5" 12
		}
		{"lvl_6" 20
		}
		{"lvl_7" 30
		}
		{"lvl_8" 42
		}
		{"lvl_9" 56
		}
		{"lvl_10" 72
		}
		(mod "mp"
			{"lvl_1" -1
			}
			{"lvl_2" -1
			}
			{"lvl_3" 0
			}
			{"lvl_4" 8
			}
			{"lvl_5" 17
			}
			{"lvl_6" 27
			}
			{"lvl_7" 38
			}
			{"lvl_8" 50
			}
			{"lvl_9" 63
			}
			{"lvl_10" 77
			}
		)
)
(define "veterancy_elite"
		{"lvl_1" 5
		}
		{"lvl_2" 11
		}
		{"lvl_3" 18
		}
		{"lvl_4" 26
		}
		{"lvl_5" 35
		}
		{"lvl_6" 45
		}
		{"lvl_7" 56
		}
		{"lvl_8" 68
		}
		{"lvl_9" 80
		}
		{"lvl_10" 93
		}
)
(define "veterancy_lvl2"   ;;;veterancy requirements reduced by how many kills are already required to be vet 2
		{"lvl_1" -1
		}
		{"lvl_2" 0
		}
		{"lvl_3" 7
		}
		{"lvl_4" 15
		}
		{"lvl_5" 24
		}
		{"lvl_6" 34
		}
		{"lvl_7" 45
		}
		{"lvl_8" 57
		}
		{"lvl_9" 70
		}
		{"lvl_10" 84
		}
)
(define "veterancy_lvl5"   ;;;veterancy requirements reduced by how many kills are already required to be vet 2
		{"lvl_1" -1
		}
		{"lvl_2" -1
		}
		{"lvl_3" -1
		}
		{"lvl_4" -1
		}
		{"lvl_5" 0
		}
		{"lvl_6" 4
		}
		{"lvl_7" 9
		}
		{"lvl_8" 12
		}
		{"lvl_9" 17
		}
		{"lvl_10" 24
		}
)